
all:
	@echo "choose explicit target :)"

tokclass_conll2003:
	clear ; time python tokclass.py > tokclass_conll2003.out

seqclass_glue-cola:
	clear ; time python seqclass.py glue-cola > seqclass_glue-cola.out

seqclass_imdb:
	clear ; time python seqclass.py imdb > seqclass_imdb.out

