
all:
	@echo "choose explicit target :)"

tokclass:
	clear ; time python tokclass.py > tokclass.out

seqclass:
	clear ; time python seqclass.py > seqclass.out

training_seqclass:
	clear ; time python training_seqclass.py > training_seqclass.out

